Epoch 1/25:   0%|                                                                                                                                                                                   | 0/402 [00:00<?, ?it/s]/usr/lib/python3/dist-packages/pandas/util/testing.py:28: FutureWarning: In the future `np.bool` will be defined as the corresponding NumPy scalar.  (This may have returned Python scalars in past versions.
  import pandas._libs.testing as _testing
Epoch 1/25:   0%|                                                                                                                                                                                   | 0/402 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 195, in <module>
    train()
  File "train.py", line 153, in train
    wandb.log({"visualization": wandb.Image(combined_row, caption=f"Epoch {epoch} - Batch {batch_idx}")})
  File "/home/kunal6/.local/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 441, in wrapper
    return func(self, *args, **kwargs)
  File "/home/kunal6/.local/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 393, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/kunal6/.local/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 383, in wrapper
    return func(self, *args, **kwargs)
  File "/home/kunal6/.local/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1871, in log
    self._log(data=data, step=step, commit=commit)
  File "/home/kunal6/.local/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1585, in _log
    self._partial_history_callback(data, step, commit)
  File "/home/kunal6/.local/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1415, in _partial_history_callback
    self._backend.interface.publish_partial_history(
  File "/home/kunal6/.local/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 674, in publish_partial_history
    data = history_dict_to_json(run, data, step=user_step, ignore_copy_err=True)
  File "/home/kunal6/.local/lib/python3.8/site-packages/wandb/sdk/data_types/utils.py", line 54, in history_dict_to_json
    payload[key] = val_to_json(
  File "/home/kunal6/.local/lib/python3.8/site-packages/wandb/sdk/data_types/utils.py", line 84, in val_to_json
    if util.is_pandas_data_frame(val):
  File "/home/kunal6/.local/lib/python3.8/site-packages/wandb/util.py", line 431, in is_pandas_data_frame
    import pandas as pd
  File "/usr/lib/python3/dist-packages/pandas/__init__.py", line 182, in <module>
    import pandas.testing
  File "/usr/lib/python3/dist-packages/pandas/testing.py", line 7, in <module>
    from pandas.util.testing import (
  File "/usr/lib/python3/dist-packages/pandas/util/testing.py", line 28, in <module>
    import pandas._libs.testing as _testing
  File "pandas/_libs/testing.pyx", line 10, in init pandas._libs.testing
  File "/usr/local/lib/python3.8/dist-packages/numpy/__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'bool'
Traceback (most recent call last):
  File "train.py", line 195, in <module>
    train()
  File "train.py", line 153, in train
    wandb.log({"visualization": wandb.Image(combined_row, caption=f"Epoch {epoch} - Batch {batch_idx}")})
  File "/home/kunal6/.local/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 441, in wrapper
    return func(self, *args, **kwargs)
  File "/home/kunal6/.local/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 393, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/kunal6/.local/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 383, in wrapper
    return func(self, *args, **kwargs)
  File "/home/kunal6/.local/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1871, in log
    self._log(data=data, step=step, commit=commit)
  File "/home/kunal6/.local/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1585, in _log
    self._partial_history_callback(data, step, commit)
  File "/home/kunal6/.local/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1415, in _partial_history_callback
    self._backend.interface.publish_partial_history(
  File "/home/kunal6/.local/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 674, in publish_partial_history
    data = history_dict_to_json(run, data, step=user_step, ignore_copy_err=True)
  File "/home/kunal6/.local/lib/python3.8/site-packages/wandb/sdk/data_types/utils.py", line 54, in history_dict_to_json
    payload[key] = val_to_json(
  File "/home/kunal6/.local/lib/python3.8/site-packages/wandb/sdk/data_types/utils.py", line 84, in val_to_json
    if util.is_pandas_data_frame(val):
  File "/home/kunal6/.local/lib/python3.8/site-packages/wandb/util.py", line 431, in is_pandas_data_frame
    import pandas as pd
  File "/usr/lib/python3/dist-packages/pandas/__init__.py", line 182, in <module>
    import pandas.testing
  File "/usr/lib/python3/dist-packages/pandas/testing.py", line 7, in <module>
    from pandas.util.testing import (
  File "/usr/lib/python3/dist-packages/pandas/util/testing.py", line 28, in <module>
    import pandas._libs.testing as _testing
  File "pandas/_libs/testing.pyx", line 10, in init pandas._libs.testing
  File "/usr/local/lib/python3.8/dist-packages/numpy/__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'bool'
